import Head from "next/head";
import Image from "next/image";

import Link from "next/link";
import Hero from "../components/sections/Hero";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Cybergence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow h-full">
        <Hero />
        <h1 className="">HomePage</h1>
        <div>
          <Link href="/search">Search Students</Link>
        </div>
        <div>
          {data.teams.map((team) => {
            return (
              <Link key={team.teamID} href={`/teams/${team.slug}`}>
                <a>{team.teamName} | </a>
              </Link>
            );
          })}
          <p>Hello</p>
        </div>
      </main>
    </>
  );
}

import fetchData from "../data/fetchData";
export const getStaticProps = async (context) => {
  const data = await fetchData();
  return {
    props: {
      data: data,
    },
  };
};
