import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Link from "next/link";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>HomePage</h1>
        <div>
          <Link href="/search">Search Students</Link>
        </div>
        <div>
          {data.teams.map((team) => {
            return (
              <Link key={team.teamID} href={`/teams/${team.slug}`}>
                <a>{team.teamName} | </a>
              </Link>
            );
          })}
        </div>
        {/* <p>{JSON.stringify(data.teams)}</p> */}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

import fetchData from "../data/fetchData";
export const getStaticProps = async (context) => {
  const data = await fetchData();
  return {
    props: {
      data: data,
    },
  };
};
